# Site settings
title: Yuqing's Homepage
email: yuqingw@andrew.cmu.edu
description: Hi! My name is Yuqing. I'm currently a graduate student at CMU, and will start my career as a software engineer next year after graduation. This site is built to demonstrate some of my work and life to you. Hope you'll be interested and get inspired!
# > # this means to ignore newlines until "baseurl:"
  #Write an awesome description for your new site here. You can edit this
  #line in _config.yml. It will appear in your document head meta (for
  #Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://locahost:4000" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown

# Google Analytics
google_analytics: UA-177679691-1